### ISSUE TITLE
gifter-labo (non-loop) 関係のブランチのファイルを綺麗にしたい

### ISSUE THREAD

**Issue by shundroid** [comozilla/Sphero-Maze-Wakuwaku#1]
ワークショップ時、
動作テスト時に使っていた余計なファイル（すみません）がないほうがわかりやすいかと。

**Comment by zigen** [comment]
余計なファイルっていうのはどれのことかな？
よかったら, 余計なファイルを `git rm` してPRしてくれた方がいいと思う。
もし, 参考になるようなファイルであれば, exampleフォルダを作ってそこにいれておいてくれると助かる。

**Comment by shundroid** [comment]
お返事ありがとうございます。

そうですね。
- ziguzagu.js (samples/sample-array.js に移行した)
- velocity.js (accelerometer の値をとってみた -> いらない)
- isStop.js (〃)

です。
ワークショップとは関係ないし、
velocity.js も isStop.js も、多分参考にならないので、
消していいですか。

**Comment by shundroid** [comment]
とりあえず、ワークショップで混乱するといけないので、
old フォルダーへ移行しておきますー。
あとはプルリクで。

**Comment by shundroid** [comment]
これで不要なファイルは消せましたので Close させていただきます。
