### ISSUE TITLE
gifter-labo (non-loop) を、default branch にしたい

### ISSUE THREAD

**Issue by shundroid** [comozilla/Sphero-Maze-Wakuwaku#10]
- Issue で、「fixed xx」としても、master ブランチでないと Close されない
- 主流はこっち（gifter-labo-non-loop）である。
- master ブランチは別のブランチとしてとっておきたい。
- master にプルリクすればいいと思ったが、別の内容だし、競合しまくってる。
#8

**Comment by zigen** [comment]
masterブランチをとっておきたいなら, 適当な名前で切っておけばいい。
もし, masterという名前を維持しておきたいけど, メインをgifter-labo-non-loopにしたいなら, 
[default branchを変更](https://help.github.com/articles/setting-the-default-branch/)してもいいかもしれない。

gifter-labo(non-loop)というブランチの名前もいまいち分かりづらいので, gifter-labo-march-27とかでもいいかもしれない。

そろそろ運用していくブランチ戦略とかも考えた方がいいかもねぇ。

**Comment by shundroid** [comment]
そうしたいです。
#2 もそうですから、先に gifter-labo (non-loop) を、gifter-labo にマージして、
それを default ブランチにしたいです。
僕には default ブランチにする権限がないため、 @dadaa さんにやっていただく形ですかね。

**Comment by dadaa** [comment]
了解，準備できたら教えてくださいませー

**Comment by shundroid** [comment]
先に送ったプルリク #11 をマージしていただけると幸いです。
その後、gifter-labo ブランチにマージして、( #2 )、
default ブランチを変えるという感じで行きたいです。

**Comment by shundroid** [comment]
default branch にするという形で、解決したため、close します。
