### ISSUE TITLE
LICENSE の取り扱い

### ISSUE THREAD

**Issue by yammmt** [comozilla/Sphero-Maze-Wakuwaku#14]
お疲れ様です。

LICENSE が個人名になってしまっているので、コモジラ名義に差し替えましょう。
とりあえず一旦 issue に立てて、プルリク投げて正す感じでしょうか。

**Comment by dadaa** [comment]
それの方法が良いかと！

**Comment by yammmt** [comment]
変えました。名義しか変えてませんが、念のためご確認頂けると幸いです。
