### ISSUE TITLE
衝突検知の設定

### ISSUE THREAD

**Issue by yammmt** [comozilla/Sphero-Maze-Wakuwaku#16]
サイボウズの ToDo リストの「空回り対策」が反映されていません。なる早で変更が必要です。

https://github.com/hrl7/SpheroController
https://github.com/hrl7/SpheroController/blob/master/main.js#L26-L32
https://github.com/orbotix/sphero.js/blob/800142d15d0a3276f3df529e8306dd295e579a16/lib/devices/sphero.js#L204-L232

**Comment by shundroid** [comment]
変更しますー

**Comment by shundroid** [comment]
書きましたー
