### ISSUE TITLE
gifter-labo(non-loop) ブランチの readme.md

### ISSUE THREAD

**Issue by shundroid** [comozilla/Sphero-Maze-Wakuwaku#6]
main.js 内関数について とか、だいぶファイルと違うので、変更したいです。

**Comment by shundroid** [comment]
connect をコメントアウト

→動かす、色をつける的な関数ではないし、
main.js で、すでに書かれている 1回しか使わないため、
混乱するかと思ったからです。

**Comment by zigen** [comment]
誤字修正とコメントアウトは, 内容的に全然違うので, 今後は別のコミットでした方がよいかも。

たとえば, 「やっぱりコメントアウトしない方がいいんじゃないか？」という話になったときに, revertしようとすると, 誤字修正まで元に戻ってしまう。コミットの粒度は人ぞれぞれだけど, 内容的に異なるときは, 分けた方がいいよ。

---

README.mdを参加者に見せる前提ならば, `connect`は使わないから, 必要ないね。
もう少し複雑になってきたら, 教える人用と参加者用のドキュメントを分けた方がいいかもね。あるいはwikiを使うのもいいと思う。

**Comment by shundroid** [comment]
コミットの話、すみません。
誤字修正の時、コミットし忘れていたので、そのまましてしまいました。
今度から、分けて行います。

connect いらないですね。
readme では、内容を大まかに説明して、「後は Wiki で」と回して、
そこで仰るとおり、教える人、参加者用で分けたいです。
マニュアルはサイボウズで作っていただいているので、
ワークショップ後、Wiki に移すのも考えたいです。

**Comment by shundroid** [comment]
ちょっと前ですが、Issue として残していなかったので、
プルリク送りましたー
#13 です。
