### ISSUE TITLE
Collised -> Collided

### ISSUE THREAD

**Issue by shundroid** [comozilla/Sphero-Maze-Wakuwaku#8]
Collised って、聞いたことないなー
と調べた結果、
動詞は、Collise でなく、Collide で、
過去形も Collided っぽいです。

マニュアルの印刷に間に合わせたいので、できるだけ早く変更したいです。

**Comment by zigen** [comment]
このissueがcloseされてないのは, masterにmergeしてないからかな？

**Comment by shundroid** [comment]
そうっぽいです。
master にコミットされないと閉じられないですよね。

どうしましょう。でも master ブランチとはコミットが競合しまくってます。
master ブランチを別のブランチに移して、gifter-labo を master にしたいです。

**Comment by shundroid** [comment]
とりあえずこの件は終わったので、Closeします
